### ISSUE TITLE
Scripts within node_modules can't be compiled because of tsconfig.json load error

### ISSUE THREAD

**Issue by kasperekt** [egoist/unplugin-swc#14]
### Issue
I want to include some packages in swc compilation process, namely `bootstrap` package files. The problem is that `joycon` package, trying to load _tsconfig.json_ file, will filter out any path that includes `node_modules` string (_[joycon code](https://github.com/egoist/joycon/blob/master/src/index.js#L81)_). When I try to run rollup script, it'll result with an error:

```
TypeError: Cannot read properties of undefined (reading 'compilerOptions')
    at getCompilerOptions (/home/user/project/node_modules/unplugin-swc/dist/index.js:2553:15)
    at async Object.transform (/home/user/project/node_modules/unplugin-swc/dist/index.js:2566:61)
    at async ModuleLoader.addModuleSource (/home/user/project/node_modules/rollup/dist/shared/rollup.js:22138:30)
```

The config:
```js
const swc = require('unplugin-swc').default;

rollup.rollup({
  plugins: [
    swc.rollup({
      exclude: /node_modules\/(?!(bootstrap)\/).*/,
    })
  ]
})
```

### Expected result

I can imagine 2 ways of handling the issue:

1. Show an error if user tries to compile file with node_modules within the path
2. Let user compile the file without an error

### Workaround

Defining _tsconfig.json_ path as an absolute path resolves the issue:

```js
const swc = require('unplugin-swc').default;
const path = require('path');

rollup.rollup({
  plugins: [
    swc.rollup({
      exclude: /node_modules\/(?!(bootstrap)\/).*/,
      tsconfigPath: path.resolve(__dirname, 'tsconfig.json')
    })
  ]
})
```

_Let me know if I can help, I can contribute to the repo but I think it's best to decide on the path first._

**Comment by egoist** [comment]
it's actually a bug here 😬
